name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
         
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
    
      - name: Install dependencies
        run: yarn
      
      - name: Run build
        run: yarn build
        
      - name: Copy dist into DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"
      
      # Override previous 'dist' content with new content
      # Execute 'yarn' inside DigitalOcean
      # Run TypeORM migrations
      # Restart Node.js server
      
